### ISSUE TITLE
go1.11: "appengine build tag is now deprecated"

### ISSUE THREAD

**Issue by arran4** [icza/session#14]
Although it would kind of need a rewrite as all the log statements panic because:
```2018/11/27 03:43:03 http: panic serving 127.0.0.1:34132: not an App Engine context
goroutine 39 [running]:
net/http.(*conn).serve.func1(0xc00026a320)
        /usr/lib/go-1.11/src/net/http/server.go:1746 +0xd0
panic(0x889120, 0xc000090cb0)
        /usr/lib/go-1.11/src/runtime/panic.go:513 +0x1b9
google.golang.org/appengine/internal.Logf(0x9ad5c0, 0xc00006ae00, 0x3, 0x93b01b, 0x34, 0xc00000c900, 0x2, 0x2)
        /home/arran/go/pkg/mod/google.golang.org/appengine@v1.3.0/internal/api_common.go:87 +0x15f
google.golang.org/appengine/log.Errorf(0x9ad5c0, 0xc00006ae00, 0x93b01b, 0x34, 0xc00000c900, 0x2, 0x2)
        /home/arran/go/pkg/mod/google.golang.org/appengine@v1.3.0/log/api.go:34 +0x73
github.com/arran4/session.(*memcacheStore).setMemcacheSession(0xc00006e900, 0x9b0080, 0xc00006e960, 0xc00001eb40)
        /home/arran/go/pkg/mod/github.com/arran4/session@v1.2.1/gae_memcache_store.go:249 +0x2c2
github.com/arran4/session.(*memcacheStore).Add(0xc00006e900, 0x9b0080, 0xc00006e960)
        /home/arran/go/pkg/mod/github.com/arran4/session@v1.2.1/gae_memcache_store.go:227 +0x83
github.com/arran4/session.(*CookieManager).Add(0xc00006aec0, 0x9b0080, 0xc00006e960, 0x9ad100, 0xc0002420e0)
        /home/arran/go/pkg/mod/github.com/arran4/session@v1.2.1/cookie_manager.go:101 +0x126
```

**Comment by icza** [comment]
Thanks for reporting this, will look into it.

**Comment by icza** [comment]
The Appengine related parts have been relocated to https://github.com/icza/gaesession, and build tags have been removed. See #17. Closing this issue.
